version: "2"
services:
  namenode:
    image: myhadoop:1
    hostname: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 22:2222
    env_file:
      - config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"
    volumes:
      - ./work:/opt/hadoop/work

  datanode:
    image: myhadoop:1
    ports:
      - "9864:9864"  # DataNode Web UI 포트
    command: ["hdfs", "datanode"]
    env_file:
      - config

  datanode2:
    image: myhadoop:1
    ports:
      - "9865:9865"  # DataNode Web UI 포트
    command: ["hdfs", "datanode"]
    env_file:
      - config

  resourcemanager:
    image: myhadoop:1
    hostname: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - config

  nodemanager:
    image: myhadoop:1
    command: ["yarn", "nodemanager"]
    env_file:
      - config
