import java.io.IOException;
import java.util.StringTokenizer;

import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.IntWritable;
import org.apache.hadoop.io.Text;
import org.apache.hadoop.mapreduce.Job;
import org.apache.hadoop.mapreduce.Mapper;
import org.apache.hadoop.mapreduce.Reducer;
import org.apache.hadoop.mapreduce.lib.input.FileInputFormat;
import org.apache.hadoop.mapreduce.lib.output.FileOutputFormat;

import org.apache.log4j.Logger;

/* 컴파일
hadoop com.sun.tools.javac.Main ~/work/IntegerCount.java
jar cf ~/work/wc.jar ~/work/IntegerCount*.class

테스트용 데이터 파일 입력
hadoop fs -mkdir /input
hadoop fs -put ~/work/data/data.csv /input

hadoop fs -rm -r hdfs://namenode/output

실행
hadoop jar ~/work/ic.jar IntegerCount /input /output

결과 데이터 확인
hdfs dfs -ls /output/
*/

public class IntegerCount {

  public static class TokenizerMapper
       extends Mapper<Object, Text, Text, IntWritable>{

    private final static IntWritable one = new IntWritable(1);
    private Text word = new Text();
    private Logger logger = Logger.getLogger(TokenizerMapper.class);

    public void map(Object key, Text value, Context context
                    ) throws IOException, InterruptedException {
      
      logger.info("TEST!!!!");
      logger.error("TEST!!!!!!!");
      String[] lines = value.toString().split("\n");

      // 각 줄 출력
      for (String line : lines) {
          logger.info(line);
          break;
      }

      StringTokenizer itr = new StringTokenizer(value.toString());
      while (itr.hasMoreTokens()) {
        word.set(itr.nextToken());
        context.write(word, one);
      }
    }
  }

  public static class IntSumReducer
       extends Reducer<Text,IntWritable,Text,IntWritable> {
    private IntWritable result = new IntWritable();

    public void reduce(Text key, Iterable<IntWritable> values,
                       Context context
                       ) throws IOException, InterruptedException {
      int sum = 0;
      for (IntWritable val : values) {
        sum += val.get();
      }
      result.set(sum);
      context.write(key, result);
    }
  }

  public static void main(String[] args) throws Exception {
    Configuration conf = new Configuration();
    Job job = Job.getInstance(conf, "word count");
    job.setJarByClass(IntegerCount.class);
    job.setMapperClass(TokenizerMapper.class);
    job.setCombinerClass(IntSumReducer.class);
    job.setReducerClass(IntSumReducer.class);
    job.setOutputKeyClass(Text.class);
    job.setOutputValueClass(IntWritable.class);
    FileInputFormat.addInputPath(job, new Path(args[0]));
    FileOutputFormat.setOutputPath(job, new Path(args[1]));
    System.exit(job.waitForCompletion(true) ? 0 : 1);
  }
}